src/Entity/Etudiant.php
<?php

namespace App\Entity;

use App\Repository\EtudiantRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EtudiantRepository::class)]
class Etudiant
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 70)]
    private $name;

    #[ORM\Column(type: 'string', length: 70)]
    private $firstname;

    #[ORM\ManyToOne(targetEntity: Section::class, inversedBy: 'etudiants')]
    private $setion;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getSetion(): ?Section
    {
        return $this->setion;
    }

    public function setSetion(?Section $setion): self
    {
        $this->setion = $setion;

        return $this;
    }
}

src/Entity/Section.php
<?php

namespace App\Entity;

use App\Repository\SectionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SectionRepository::class)]
class Section
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $Designation;

    #[ORM\OneToMany(mappedBy: 'setion', targetEntity: Etudiant::class)]
    private $etudiants;

    public function __construct()
    {
        $this->etudiants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDesignation(): ?string
    {
        return $this->Designation;
    }

    public function setDesignation(string $Designation): self
    {
        $this->Designation = $Designation;

        return $this;
    }

    /**
     * @return Collection<int, Etudiant>
     */
    public function getEtudiants(): Collection
    {
        return $this->etudiants;
    }

    public function addEtudiant(Etudiant $etudiant): self
    {
        if (!$this->etudiants->contains($etudiant)) {
            $this->etudiants[] = $etudiant;
            $etudiant->setSetion($this);
        }

        return $this;
    }

    public function removeEtudiant(Etudiant $etudiant): self
    {
        if ($this->etudiants->removeElement($etudiant)) {
            // set the owning side to null (unless already changed)
            if ($etudiant->getSetion() === $this) {
                $etudiant->setSetion(null);
            }
        }

        return $this;
    }
    public function __toString(): string{
        return $this->Designation;
    }
}

src/Form/EtudiantType.php
<?php

namespace App\Form;

use App\Entity\Etudiant;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EtudiantType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('firstname')
            ->add('setion')
            ->add('Submit', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Etudiant::class,
        ]);
    }
}

src/Controller/EtudiantController.php
<?php

namespace App\Controller;

use App\Entity\Etudiant;
use App\Entity\Section;
use App\Form\EtudiantType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/etudiant')]

class EtudiantController extends AbstractController
{
    #[Route('/', name: 'etudiant')]
    public function index(ManagerRegistry $doctrine): Response
    {
        $repository = $doctrine->getRepository(Etudiant::class);
        $etudiants = $repository->findAll();
        return $this->render('etudiant/index.html.twig', [
            'etudiants' => $etudiants,
        ]);
    }
    #[Route('/edit/{id?0}', name: 'etudiant.edit')]
    public function addEtudiant(ManagerRegistry $doctrine, Etudiant $etudiant = null, Request $request): Response
    {
        $new = false;

        if (!$etudiant){
            $etudiant = new Etudiant();
            $new = true;
        }
        $form = $this->createForm(EtudiantType::class, $etudiant);

        $form->handleRequest($request);

        if($form->isSubmitted()){
            $entityManager = $doctrine->getManager();
            $entityManager->persist($etudiant);
            $entityManager->flush();

            if ($new){
                $message =" a été ajoutée avec succès";
            }else{
                $message =" a été mise à jour avec succès";
            }

            $this->addFlash('success', $etudiant->getName(). $message);
            return $this->redirectToRoute('etudiant');
        }else{
            return $this->render('etudiant/add-etudiant.html.twig', [
                'form' => $form->createView()
            ]);
        }
    }

#[Route('/delete/{id}', name: 'etudiant.delete')]
public function removeEtudiant(ManagerRegistry $doctrine, Etudiant $etudiant = null):Response
{
    if($etudiant){
        $manager = $doctrine->getManager();
        $manager->remove($etudiant);
        $manager->flush();
        $this->addFlash('success', ' Etudiant supprimé avec succès');
    }else{
        $this->addFlash('error', "L'étudiant n'existe pas");
    }
    return $this->redirectToRoute("etudiant");

}

}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}

    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/etudiant/add-etudiant.html.twig
{% extends 'template.html.twig' %}

{% block body %}
    {{ form_start(form) }}
    <div class="row">
        <div class="col">{{ form_row(form.firstname) }}</div>
        <div class="col">{{ form_row(form.name) }}</div>
    </div>
    {{ form_rest(form) }}
{% endblock %}

{% block title %}
    formulaire
{% endblock %}

templates/etudiant/index.html.twig
{% extends 'template.html.twig' %}
{% block pageTitle %}
    Etudiants
{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('styles/styles.css') }}">
{% endblock %}
{% block title %}
liste des etudiants
{% endblock %}
{% block body %}
    <a href="{{ path('etudiant.edit') }}">Ajouter un étudiant:</a>
    <table class="table" id="table-etudiant">
        <tr class="table-active">
            <th>Firstname</th>
            <th>Name</th>
            <th>Section</th>
            <th>Action</th>
        </tr>
        {% for etudiant in etudiants %}
            <tr onclick="highlight()" class="table-{% if loop.index is odd %}danger{% else %}warning{% endif %}">
                <td>{{ etudiant.firstname | capitalize }}</td>
                <td>{{ etudiant.name | capitalize }}</td>
                <td>{% if etudiant.setion %}{{ etudiant.setion.designation }}{% else %} pas encore{% endif %}</td>
                <td>
                    <a href="{{ path('etudiant.edit',{id : etudiant.id}) }}">edit</a>
                    <a href="{{ path('etudiant.delete',{id : etudiant.id}) }}">delete</a>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}
{% block javascripts %}
    <script src="{{ asset('js/script.js') }}"> </script>
{% endblock %}

templates/fragments/cards.html.twig
<div class="row">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">Title</h5>
                <h6 class="card-subtitle mb-2 text-muted">sous-Titre</h6>
                <p class="card-text"> Details en paragraphe </p>
                <a href=" " class="card-link">Détails</a>
                <a href="" class="card-link">Delete</a>
                <a href="" class="card-link">Edit</a></div>
        </div>
</div>

templates/fragments/tables.html.twig
<table class="table">
    <tr class="table-active">
        <th>Firstname</th>
        <th>Name</th>
        <th>Age</th>
        <th>Message</th>
    </tr>
    {% for user in users %}
        <tr class="table-{% if loop.index is odd %}danger{% else %}warning{% endif %}">
            <td>{{ user.firstname | capitalize }}</td>
            <td>{{ user.name | capitalize }}</td>
            <td>{{ user.age |capitalize }}</td>
            <td>{{ render(controller('App\\Controller\\FirstController::passerMessage', {name: user.firstname})) }}</td>
        </tr>
    {% endfor %}
</table>

templates/template.html.twig
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}
            Examen tp
        {% endblock %}
    </title>
    <link href="{{ asset('node_modules/bootstrap/dist/css/bootstrap.css') }}" rel="stylesheet" />
    {% block stylesheets %}
    {% endblock %}
</head>
<body>
<h1>
    {% block pageTitle %}
        Template
    {% endblock %}
</h1>
<div class="card mb-4">
    <div class="card-body">
        {% for message in app.session.flashBag.get('info') %}
            <div class="alert alert-info">{{ message }}</div>
        {% endfor %}
        {% for message in app.session.flashBag.get('success') %}
            <div class="alert alert-success">{{ message }}</div>
        {% endfor %}
        {% for message in app.session.flashBag.get('error') %}
            <div class="alert alert-danger">{{ message }}</div>
        {% endfor %}

        {% block body %}
            Template body
        {% endblock %}
    </div>
</div>

{% block javascripts %}
{% endblock %}
</body>
</html>